### ISSUE TITLE
Implement of self loop

### ISSUE THREAD

**Issue by DengChan** [qipeng/gcn-over-pruned-trees#13]
Dear authors:
         I have a question about the implement of self loop.
         In  "tree.py:  line 173-175",we have set adj[i,i]=1,</br>
`if self_loop:
        for i in idx:
            ret[i, i] = 1`  </br>
         And I think the information of the node itself have been contained by the bmm operation for adj and gcn_input,just like "gcn.py : line 166":</br>
`Ax = adj.bmm(gcn_inputs)`   </br>
       But why we still use "gcn.py : line 168" to do self loop ?</br>
`AxW = AxW + self.W[l](gcn_inputs)`

**Comment by qipeng** [comment]
This is because `self_loop` is turned off in our code here:
https://github.com/qipeng/gcn-over-pruned-trees/blob/master/model/gcn.py#L79

That was actually a feature that we were exploring in our preliminary experiments, but we ended up realizing that separate parameterization didn't really help the final performance, thus opted to stay with the simplest GCN formulation.
