### ISSUE TITLE
Higher Loss Value

### ISSUE THREAD

**Issue by ZohaibRamzan** [qipeng/gcn-over-pruned-trees#27]
![2021-03-29](https://user-images.githubusercontent.com/48449038/112877416-044d5280-90c7-11eb-8d29-ba723215e036.png)
I am training the model with prune_k=-1, but i am getting very high loss values. What can be the problem indeed?
Kindly give insight into it.

**Comment by Youoo1** [comment]
I don't know that why these recall and F1 are 0?
![Uploading 2021-06-10 14-33-59屏幕截图.png…]()

**Comment by Youoo1** [comment]
I don't know that why these recall and F1 are 0?
![2021-06-10 14-33-59屏幕截图](https://user-images.githubusercontent.com/72395705/121476238-fe45ed00-c9f8-11eb-8361-0438f424bc72.png)

**Comment by ZohaibRamzan** [comment]
> I don't know that why these recall and F1 are 0?
> ![2021-06-10 14-33-59屏幕截图](https://user-images.githubusercontent.com/72395705/121476238-fe45ed00-c9f8-11eb-8361-0438f424bc72.png)

This is because the dataset has not enough data to work on. It contains the examples of just one type i.e. 'no-relation'.

**Comment by Youoo1** [comment]
yes!I am using the demo dataset he gave me. Do you have the full dataset for traced? It's so hard to find.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qipeng/gcn-over-pruned-trees] Higher Loss Value (#27)





  
I don't know that why these recall and F1 are 0?
 
  
This is because the dataset has not enough data to work on. It contains the examples of just one type i.e. 'no-relation'.

**Comment by Tsinghua-ai** [comment]
请问，对应的论文去哪找呀

**Comment by ZohaibRamzan** [comment]
I can not share dataset because it is licensed.
